# Generated by Django 5.0.4 on 2024-05-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TongDoanhThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_thu_tu_hoa_don', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tong_luong_nhan_vien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tong_vat_tu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tong_doanh_thu', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
