# Generated by Django 5.0.4 on 2024-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('ma_nhan_vien', models.AutoField(primary_key=True, serialize=False)),
                ('ten_nhan_vien', models.CharField(max_length=100)),
                ('que_quan', models.CharField(max_length=100)),
                ('so_cccd', models.CharField(max_length=12)),
                ('dia_chi_thuong_tru', models.CharField(max_length=200)),
                ('chuc_vu', models.CharField(choices=[('Nhân viên', 'Nhân viên'), ('Kỹ sư', 'Kỹ sư'), ('Quản đốc', 'Quản đốc')], max_length=100)),
            ],
        ),
    ]
