# Generated by Django 5.0.4 on 2024-05-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tai_khoan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nguoidung',
            options={},
        ),
        migrations.AlterModelManagers(
            name='nguoidung',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='email',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='username',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='ten_cong_ty',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='ma_so_thue',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
