# Generated by Django 5.0.4 on 2024-05-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cham_cong', '0002_alter_chamcong_chuc_vu_dam_nhan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamcong',
            name='chuc_vu_dam_nhan',
        ),
        migrations.RemoveField(
            model_name='chamcong',
            name='tong_cong',
        ),
        migrations.AddField(
            model_name='chamcong',
            name='so_ngay_chu_nhat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chamcong',
            name='so_ngay_thu_bay',
            field=models.IntegerField(default=0),
        ),
    ]
