# Generated by Django 5.0.4 on 2024-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cham_cong', '0003_remove_chamcong_chuc_vu_dam_nhan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamcong',
            name='so_gio_lam_viec',
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='ngay_bat_dau',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='ngay_ket_thuc',
            field=models.DateField(),
        ),
    ]
