# Generated by Django 5.0.4 on 2024-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cham_cong', '0004_remove_chamcong_so_gio_lam_viec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamcong',
            name='luong',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='chamcong',
            name='so_gio_lam_viec',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='chamcong',
            name='tong_cong',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='ngay_bat_dau',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='ngay_ket_thuc',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='so_ngay_chu_nhat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='so_ngay_thu_bay',
            field=models.IntegerField(),
        ),
    ]
