# Generated by Django 5.0.4 on 2024-05-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_lap', models.DateTimeField()),
                ('ma_tien_te', models.CharField(choices=[('VND', 'VND'), ('USD', 'USD')], max_length=3)),
                ('hinh_thuc_thanh_toan', models.CharField(choices=[('Tiền mặt', 'Tiền mặt'), ('Chuyển khoản', 'Chuyển khoản')], max_length=20)),
                ('email_nguoi_ban', models.EmailField(blank=True, max_length=254, null=True)),
                ('sdt_nguoi_ban', models.CharField(blank=True, max_length=15, null=True)),
                ('stk_nguoi_ban', models.CharField(blank=True, max_length=20, null=True)),
                ('nh_nguoi_ban', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cong_ty', models.CharField(max_length=100)),
                ('ma_so_thue', models.CharField(max_length=20)),
                ('dia_chi', models.CharField(max_length=200)),
                ('sdt', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tau',
            fields=[
                ('ma_tau', models.AutoField(primary_key=True, serialize=False)),
                ('ten_tau', models.CharField(max_length=100)),
                ('dien_giai', models.TextField()),
                ('tien_truoc_thue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('thue_suat', models.DecimalField(choices=[(8.0, '8%'), (10.0, '10%')], decimal_places=2, default=8.0, max_digits=4)),
                ('tien_thue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tien_sau_thue', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoa_don.hoadon')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoa_don.khachhang')),
                ('tau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoa_don.tau')),
            ],
        ),
    ]
