# Generated by Django 5.0.4 on 2024-05-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoa_don', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatTu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_vat_tu', models.CharField(max_length=100)),
                ('khoi_luong', models.DecimalField(decimal_places=2, max_digits=12)),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('he_so_cong', models.DecimalField(choices=[(1.0, '1.00'), (2.0, '2.00'), (3.0, '3.00')], decimal_places=2, max_digits=4)),
                ('tau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vattu', to='hoa_don.tau')),
            ],
        ),
        migrations.CreateModel(
            name='QuyetToanVatTu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoa_don.tau')),
                ('vat_tu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vat_tu.vattu')),
            ],
        ),
    ]
